name: Update k8s image
description: Updates a container tag inside a Kubernetes manifest
branding:
  color: blue
  icon: anchor

inputs:
  manifest-path:
    description: Location of the manifest that will be updated
    required: true
  new-image-tag:
    description: New image tag
    default: '${{github.sha}}'
    required: false
  container-name:
    description: Name of the container that references the image to replace
    required: true
outputs:
  old-image-tag:
    description: 'Previous image tag'

runs:
  using: 'node16'
  main: 'dist/index.js'
